apiVersion: v2
name: scalyr-agent
description: A Helm chart for deploying the Scalyr agent
type: application
version: 0.2.44
appVersion: 2.2.15
keywords:
  - scalyr
  - logging
  - monitoring
  - metrics
home: https://github.com/scalyr/helm-scalyr
icon: https://app.scalyr.com/s2/src/img/logo-reverse.png
sources:
  - https://github.com/scalyr/helm-scalyr
maintainers:
  - name: scalyr
    email: support@scalyr.com
    url: https://github.com/scalyr
  - name: dploeger
    email: develop@dieploegers.de
    url: https://github.com/dploeger
